import { NextResponse } from "next/server";

export async function GET() {
  const fleetData = [
    {
      slug: "genesis-g90",
      name: "Genesis G90",
      price: "$132.0/hr",
      category: "Executive Car",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/genesis/genesis.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$132.0/Hour",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1056.0/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/genesis/left.png",
        "https://sydneylimousineservice.com/img/fleets/genesis/interior.png",
        "https://sydneylimousineservice.com/img/fleets/genesis/front.png",
        "https://sydneylimousineservice.com/img/fleets/genesis/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/genesis/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/genesis/back.png",
      ],
      whyChoose: [
        `The Luxury Sedan Genesis is one of the popular spacious car for four people travelling comfortably for your airport transfers, corporate transfers or any other point to point transfer services.`,
        `It can be hired for your wedding car service for lifetime special day. You should deserve to feel like royalty on your special day forever, and make your weeding memorable when you book luxury Genesis. Our elegant Genesis is also suitable for your special day hiring for greatest expectation, so whether you can choose Genesis from our luxury fleet, and we will arrive at your venue in elegant and comfort.`,
        `We offer Genesis luxury sedan limo hire at very competitive prices for corporate travellers in the corporate community. Our Genesis chauffeur will provide you with the very best limousine service. It is also suitable transportation for all corporate occasions, business meeting, seminars, business launch and corporate gaming functions.`,
        `It can be toured to the Blue Mountain and Hunter Valley with a scenic smooth drive that will reduce your stress-free travel which you will get to ride in comfort and style. Our chauffeurs are well experienced for sightseeing tour in Blue Mountain and Hunter Valley with clean and comfortable with air-conditioned Genesis limo.`,
      ],

      overview: [
        `The Genesis is a large luxury sedan that is the latest-generation Genesis platform, but it’s been enlarged to provide a sedan limousine. Under the hood is a 3.8-liter V6 generating include eight-speed automatic transmission with manual shift mode and a five-star safety rating. Power is sent to the rear wheels through an eight-speed automatic transmission.`,
        `Inside the Genesis, the highly adjustable front seats are a pleasure to settle into no matter what the weather, as the built-in ventilation system circulates heated or cooled air through the perforated leather upholstery. Rear seat passengers will enjoy the vast amount of legroom, especially since the outboard seats recline. These, too, are heated and (in Ultimate trim) cooled, and the central armrest folds down to reveal a bevy of controls for seat lumbar, rear power shade and rear seat entertainment displays.`,
        `On the highway, the Genesis sedan limo drives like a large luxury sedan should. It’s exceptionally quiet at speed, and the ride is soft and comfortable. The Genesis interior is intuitively designed to create a harmonious experience.`,
      ],
      amenities: [
        "Top of the ultimate Luxury",
        "Exceptionally quiet at speed with soft ride and comfort",
        "The Genesis interior is intuitively designed to create a harmonious experience.",
        "Wood grain touch and aluminum combination in the dash and door",
        "From button placement, to tactile response, and overall interior layout is excellent.",
        "Optimised for exceptional comfort and convenience.",
        "It offers anti-theft system for your safety.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Mercedes Class SUV Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
      ],
    },
    {
      slug: "chrysler-300C",
      name: "Chrysler 300C",
      price: "$132.0/hr",
      category: "Executive Car",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image: "https://sydneylimousineservice.com/img/fleets/chrysler/front.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$132.0/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1056.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/chrysler/left.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler/interior.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler/front.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler/back.png",
      ],

      whyChoose: [
        `The Luxury Sedan Chrysler 300C is one of the popular spacious car for four people travelling comfortably for your airport transfers, corporate transfers or any other point to point transfer services.`,
        `It can be hired for your wedding car service for lifetime special day. You should deserve to feel like royalty on your special day forever, and make your weeding memorable when you book luxury sedan Chrysler 300C. Our elegant Chrysler 300C is also suitable for your special day hiring for greatest expectation, so whether you can choose Chrysler from our luxury fleet, and we will arrive at your venue in elegant and comfort.`,
        `We offer Chrysler luxury sedan limo hire at very competitive prices for corporate travellers in the corporate community. Our Chrysler's chauffeur will provide you with the very best limousine service. It is also suitable transportation for all corporate occasions, business meeting, seminars, business launch and corporate gaming functions.`,
        `It can be toured to the Blue Mountain and Hunter Valley with a scenic smooth drive that will reduce your stress-free travel which you will get to ride in comfort and style. Our chauffeurs are well experienced for sightseeing tour in Blue Mountain and Hunter Valley with clean and comfortable with air-conditioned Chrysler sedan limo.`,
      ],
      overview: [
        `The Chrysler 300C is a sedan of ultimate luxury with a V6 petrol engine, with the previous diesel and 5.7-litre Hemi V8 options no longer offered. Performance enthusiasts are specifically catered for with the unique-for-Australia 300 SRT. Even in base trim, the 300C is loaded with a generous level of standard equipment, including 18-inch alloys, full  leather interior, dual-zone climate control, cruise control, heated front and rear seats and an 8.4-inch colour touchscreen multimedia system with sat nav, digital radio, a reverse camera and a 9-speaker Alpine audio set-up.`,
        `The Luxury model builds on that a bit more bling – both inside and out – including chrome exterior highlights, 20-inch alloys, ventilation for the front seats, quilted leather trim and a host of active safety features such as adaptive cruise control with lane departure and forward collision warnings.`,
        `The 300C packs a lot of quantity into its cabin, particularly in this Luxury specification. The quilted leather seats and contrasting colours of the cockpit – with cream and black leather mixed with raw wood grain and aluminium highlights in the dash and door surrounds – give the cockpit a genuine sense of luxury, while the blue-lit ambient lighting and large touch screen add an element of modernity to the overall appearance. This is a great car for Corporate Airport Transfer.`,
      ],
      amenities: [
        "Luxurious leather-trimmed seats",
        "Onboard DVD players",
        "Raw wood grain and aluminium highlights in the dash and door surrounds",
        "USB/Phone charger and cup holders available",
        "Bluetooth's connectivity, laptop and mobile phone charger facility",
        "Heated front and rear seats",
        "Perceived as style icon in luxury car segment",
      ],
      servicesOffered: [
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Chrysler Sedan Limousine Service",
        "Wedding Limousine",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Limo Hire",
        "Door to Door Services",
        "Chrysler Limousine Hire",
        "Group Tour Services",
        "Corporate Car Hire",
      ],
    },
    {
      slug: "tesla-model-s",
      name: "Tesla Model S",
      price: "$132.0/hr",
      category: "Executive Car",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/tesla-model-s.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$132.0/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1056.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/left.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/interior.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/back.png",
      ],
    },
    {
      slug: "lexus-es-300h",
      name: "Lexus ES 300h",
      price: "$132.0/hr",
      category: "Executive Car",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/lexus-es-300h/lexus-es-300h.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$132.0/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1056.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/left.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/interior.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/tesla-model-s/back.png",
      ],
      whyChoose: [
        "The top-tier luxury Lexus ES 300h is a highly sought-after spacious car, designed for the comfort of four passengers during airport transfers, corporate travels, or any other point-to-point transfer services.",
        "The Lexus ES 300h offers an elevated level of luxury and spaciousness, ensuring a comfortable journey for occupants along with ample storage space for large luggage.",
        "With its high-performance and elegant design, the Lexus ES 300h provides a luxurious transportation experience.",
        "For those seeking sophistication and luxury, our Lexus ES 300h is an excellent choice for hire in Sydney, ideal for special occasions such as impressing a date or important corporate meetings.",
        "Whether you are a frequent corporate traveler or occasional business voyager, the Lexus ES 300h stands out as a professional and reliable choice.",
        "Make your wedding day truly memorable by choosing the Lexus ES 300h as your wedding car.",
        "Experience the feeling of royalty on your special day with the Lexus ES 300h, adding elegance and comfort to your wedding transportation.",
        "Our competitive prices for Lexus ES 300h luxury sedan limo hire cater to corporate travelers within the business community.",
        "Our chauffeurs ensure the highest level of limousine service, making the Lexus ES 300h a suitable choice for corporate occasions, business meetings, seminars, business launches, and corporate gaming functions.",
        "Plan a scenic drive to the Blue Mountains or Hunter Valley in the Lexus ES 300h, enjoying a smooth and stress-free journey in comfort and style.",
      ],
      overview: [
        "The Lexus ES 300h cabin defines top-tier luxury, featuring exquisite materials and finishes throughout.",
        "Exceptional comfort is guaranteed, with options such as reclining rear seats for an ultimate limousine ride.",
        "The Lexus ES 300h showcases elegant and dynamic design, with its iconic exterior star emblem.",
        "This luxury sedan combines advanced technology and efficiency, making it a desirable choice in the limousine industry.",
        "The latest Lexus ES 300h boasts a streamlined appearance, with notable features such as a large front grille inspired by cutting-edge design concepts.",
        "LED lights are exclusively used both inside and outside, setting new standards in the automotive industry.",
        "Sculpted flanks, integrated exhaust tips, and a spacious glass roof highlight the design elements.",
        "In addition to the sedan model, the long-wheelbase variant offers a V222 chassis code, focusing on delivering a smooth, quiet, and roomy interior.",
        "The Lexus ES 300h is equipped with high-quality materials, advanced technology, and safety features, making it the perfect sedan limousine for special transfers such as wedding services, anniversaries, and official hierarchical transfers.",
      ],
      amenities: [
        "Received as a style icon in the luxury car segment.",
        "Intelligent electronic system.",
        "Facility of redefined sensor systems creating a safe distance between the front and the next car.",
        "Night view assist system providing clear visibility in fog, dust, or darkness.",
        "Equipped with airbags for both driver and passenger safety.",
        "4-Wheel ABS (Anti-Lock Braking System) preventing sudden skidding.",
        "Integration with a 7-surround music system.",
        "Wood grain and aluminum highlights in the dash and door surrounds.",
        "Split view facility, an innovative technology displaying different images on a single screen.",
      ],
      serviceOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Wedding Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Lexus ES 300h Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "Lexus ES 300h Limo",
      ],
    },
    {
      slug: "mercedes-s-class",
      name: "Mercedes S Class",
      price: "$166.5/hr",
      category: "European Luxury Sedan",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/mercedes-s-class.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$166.5/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1332.0 /DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/left.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/interior.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/front.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-s-class/back.png",
      ],
      whyChoose: [
        "The top of the luxury Mercedes-Benz S Class is a popular spacious car for four people travelling comfortably for airport transfers, corporate transfers, or any other point-to-point transfer services.",
        "The Mercedes S-Class has the highest level of luxury atmosphere with spaciousness, enhancing travelling comfort on the rear seats and offering a spacious boot to accommodate large luggage.",
        "With high performance and elegant design, the Mercedes-Benz S Class provides luxurious transportation for any special occasion where you want to impress, whether it's a date or an important corporate meeting.",
        "The Mercedes S-Class is ideal for corporate executives, whether traveling extensively or occasionally for work, making it a professional choice for regular use.",
        "It is the perfect choice for wedding car services, ensuring that you feel like royalty on your special day. Make your wedding memorable by booking a luxury Mercedes S-Class sedan.",
        "Our elegant Mercedes S-Class is suitable for your special day, offering the highest level of comfort and style as you arrive at your venue.",
        "We offer Mercedes S Class luxury sedan limo hire at very competitive prices, especially for corporate travellers in the corporate community.",
        "The Mercedes S-Class is also suitable for all corporate occasions, such as business meetings, seminars, business launches, and corporate gaming functions.",
        "You can enjoy a scenic, smooth drive to destinations like the Blue Mountain or Hunter Valley in the Mercedes S-Class, reducing stress and providing a comfortable and stylish travel experience.",
      ],
      overview: [
        "The Mercedes S-Class cabin defines top luxury, featuring exquisite materials and finishes throughout. Comfort is exceptional, with options such as reclining rear seats for the ultimate limousine ride.",
        "The iconic star on the body and the elegant, dynamic design make the Mercedes S-Class a study in luxury. It has long been the default limousine choice, with the latest model pushing technology and efficiency to new levels.",
        "The newest Mercedes S-Class features a more streamlined appearance, with a large front grille inspired by the F700 Concept car and exclusive LED lights inside and out—a first in the automotive industry.",
        "The design of the Mercedes S-Class includes strong converging character lines, integrated exhaust tips, and a large glass roof, giving it a sculpted and modern look.",
        "The Mercedes S-Class offers a Long-wheelbase variant, using chassis code V222, catering to the growing market of customers who prefer to be chauffeured.",
        "The long-wheelbase S-Class offers a smooth, quiet, and refined ride with a roomy interior, high-quality materials, and advanced technology, making it a top choice for special transfers, wedding services, anniversary services, and official hierarchical transfers.",
      ],
      amenities: [
        "Perceived as a style icon in the luxury car segment.",
        "Intelligent electronic system for enhanced vehicle control and safety.",
        "Redefined sensor systems that maintain a safe distance between the front and the next car.",
        "Night view assist system providing clear vision of the road ahead in fog, dust, or extra dark conditions.",
        "Equipped with airbags on both the driver and passenger sides for enhanced safety.",
        "4-Wheel ABS (Anti Lock Braking System) that prevents sudden skidding.",
        "Integration with a 7-surround music system for an immersive audio experience.",
        "Wood grain and aluminium highlights in the dash and door surrounds for an elegant interior.",
        "Split view facility, an innovative technology allowing different images to be viewed on a single screen.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Mercedes S Class Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "Mercedes S Class Limo",
      ],
    },
    {
      slug: "audi-a8",
      name: "Audi A8",
      price: "$166.5/hr",
      category: "European Luxury Sedan",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/audi-a8/audi-a8.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$166.5/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1332.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/audi-a8/left.png",
        "https://sydneylimousineservice.com/img/fleets/audi-a8/interior.png",
        "https://sydneylimousineservice.com/img/fleets/audi-a8/front.png",
        "https://sydneylimousineservice.com/img/fleets/audi-a8/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/audi-a8/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/audi-a8/back.png",
      ],
      whyChoose: [
        "The luxury Audi A8 is a top luxury car in the Audi fleet, ideal for airport transfers, corporate transfers, and other point-to-point services. It provides a spacious and comfortable experience for up to four people.",
        "The Audi A8 offers a spacious interior and boot space, making it perfect for accommodating large luggage. Rear seat passengers can enjoy maximum comfort, enhancing the overall travel experience.",
        "With high performance and elegant design, the Audi A8 Series offers a luxurious ride for any occasion. Whether it’s a special event or a corporate meeting, it guarantees sophistication and style.",
        "Hire the Audi A8 in Sydney to elevate your special occasions, such as weddings, corporate meetings, or any event where you want to make a strong impression.",
        "The Audi A8 is a perfect choice for wedding car services, allowing you to feel like royalty on your special day. Arrive at your venue in style and make your wedding day truly memorable.",
        "At competitive prices, the Audi A8 is an excellent option for corporate travellers, providing professional limousine service for business meetings, seminars, and corporate events.",
        "Enjoy a scenic and smooth drive with the Audi A8 to destinations like the Blue Mountain or Hunter Valley. Its comfortable ride reduces stress and lets you travel in style.",
      ],
      overview: [
        "The iconic looks of the Audi A8 L don’t need an introduction. A bold single frame grille, dazzling LED headlights, and available 21-inch wheels add captivating details that are at the heart of the world’s greatest designs.",
        "Greatness is achieved by those with the courage to reimagine the possible. Those who defy convention and push performance to the limits. Innovate intelligent technology that anticipates drivers' needs, and design silhouettes that defy trends and the wind. This is the spirit that drives Audi.",
        "The world is changing, and mobility is changing with it. The Audi A8 L features full LED headlights, MMI Navigation plus with voice control system, and Audi advanced keyless start, stop, and entry.",
        "The Audi A8 L offers a BOSE Surround Sound System with 14 speakers, Audio Pilot noise-compensation, and 630 watts, delivering a premium sound experience.",
        "Audi exclusive offers many ways to experience the joy of owning an Audi that is truly unmistakable. Audi's engineers and designers challenge convention, pioneering the ways you connect with your Audi.",
        "The precise level of detail applied to every element throughout the cabin is a benchmark of refinement, creating an unparalleled driving experience.",
        "The Audi A8 is the perfect choice for special transfers, wedding services, and official hierarchical transfers.",
      ],
      amenities: [
        "Considered as ultimate luxury on wheels.",
        "Raw wood grain and aluminium highlights in the dash and door surrounds add a touch of elegance.",
        "A powerful 4.2 FSI V8 engine offers an output of 372 HP, ensuring pure power.",
        "Audi Servotronic speed-sensitive power steering varies assistance based on vehicle speed.",
        "Anti-theft vehicle alarm system with immobiliser and blinking theft deterrent light for added security.",
        "Rear fog light and Headlight washers – high pressure, retractable, and heated for optimal visibility.",
        "LED ambient interior lighting and a voice recognition system enhance the driving experience.",
        "Dual front sun visors with lighted vanity mirrors for both the driver and front passenger.",
        "In-dash DVD and CD player along with Audi MMI Navigation plus with voice control system for advanced entertainment and navigation.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Audi A8 Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "Audi A8 Limo",
      ],
    },
    {
      slug: "bmw-7-series",
      name: "BMW 7 Series",
      price: "$166.5/hr",
      category: "European Luxury Sedan",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/bmw-7-series.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$166.5/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1332.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/left.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/interior.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/front.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/front.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-7-series/back.png",
      ],
      whyChoose: [
        "The luxury BMW 7 Series is a top luxury car in the BMW fleet, offering a spacious and comfortable experience for four people traveling for airport transfers, corporate transfers, or point-to-point services.",
        "The BMW 7 Series creates a luxurious atmosphere with its spacious interior and rear seat comfort, along with a large boot to accommodate big luggage, ensuring a smooth and comfortable travel experience.",
        "With high performance and elegant design, the BMW 7 Series provides luxurious transportation for any special occasion where you want to impress, whether it’s a date or an important corporate meeting.",
        "The BMW 7 Series is ideal for corporate executives, whether traveling extensively or occasionally for work, making it a professional choice for regular use.",
        "It is the perfect choice for wedding car services, allowing you to feel like royalty on your special day. Make your wedding memorable by booking a luxury BMW 7 Series sedan.",
        "Our elegant BMW 7 Series is suitable for special day hires, offering the highest level of comfort and style as you arrive at your venue.",
        "We offer BMW 7 Series luxury sedan limo hire at very competitive prices, especially for corporate travelers in the corporate community.",
        "The BMW 7 Series is also suitable for all corporate occasions, such as business meetings, seminars, business launches, and corporate gaming functions.",
        "You can enjoy a scenic, smooth drive to destinations like the Blue Mountain or Hunter Valley in the BMW 7 Series, reducing stress and providing a comfortable and stylish travel experience.",
      ],
      overview: [
        "The BMW 7 Series is typical BMW design in its most elegant form, with a forward-surging front, extended side view, and powerful rear, radiating a natural and authoritative presence from every angle.",
        "The BMW 7 Series reaches new heights in technology, comfort, and performance, seamlessly integrating them into a luxury experience for both drivers and passengers.",
        "With more innovations than any other car in its class and a wealth of athleticism, the 7 Series effortlessly takes the lead for the future of luxury travel.",
        "Passengers in the rear seats of the BMW 7 Series enjoy a generous amount of space during their journey, adding to the luxurious experience.",
        "The active chassis technology of the Executive Drive Pro option provides a driving experience that is both comfortable and dynamic in every situation.",
        "Ambient light design, combined with innovative comfort and entertainment functions, ensures a supreme level of relaxed traveling pleasure in the BMW 7 Series.",
        "The BMW 7 Series is a great choice for limousine services, offering an immaculate vehicle for special transfers such as wedding services, anniversary services, and hierarchical official transfers.",
      ],
      amenities: [
        "Consideration as a full-size ultimate European luxury vehicle.",
        "Full-LED headlights, a prominent BMW kidney grille, and a modified front for a striking appearance.",
        "Laminated windows and under body armor for added protection.",
        "Emergency front windscreen exit in case such a situation arises.",
        "Parking-assist technology that can automatically park the car.",
        "Integral active four-wheel steering system for enhanced control.",
        "Dynamic damper control and ambient cabin lighting for a comfortable ride and luxurious atmosphere.",
        "The six- or eight-speed automatic transmission provides driving comfort to its drivers.",
        "The most luxurious form of efficiency, turning every journey into a unique experience.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "BMW 7 Series Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "BMW 7 Series Limo",
      ],
    },

    {
      slug: "audi-Q7-(suv)",
      name: "Audi Q7 (SUV)",
      price: "$133.2/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/audi-q7/audi-q7.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$133.2/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1065.6/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/audi-q7/left.png",
        "https://sydneylimousineservice.com/img/fleets/audi-q7/interior.png",
        "https://sydneylimousineservice.com/img/fleets/audi-q7/front.png",
        "https://sydneylimousineservice.com/img/fleets/audi-q7/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/audi-q7/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/audi-q7/back.png",
      ],
      whyChoose: [
        "The European Luxury SUV Audi Q7 is a popular spacious car for a family of four, offering room for four pieces of large luggage, making it ideal for airport transfers, cruise ship transfers, or point-to-point services.",
        "The Audi Q7 delivers dynamic performance with a powerful drive and an elegant interior featuring sophisticated leather seats, providing a comfortable and stylish travel experience.",
        "The Q7 comfortably accommodates up to 6 passengers, but for four people with large luggage, the third-row seats can be individually folded down at the touch of a button to create a generous luggage compartment.",
        "The Audi Q7 can be hired for wedding car services, allowing you to feel like royalty and make your special day memorable in this luxury SUV.",
        "Our elegant Audi Q7 is a perfect choice for special day hires, ensuring that you arrive at your venue in comfort and style.",
        "We offer Audi Q7 luxury SUV limo hire at competitive prices, making it an excellent option for corporate travelers in the corporate community.",
        "The Audi Q7 is suitable for transportation to corporate events, including business meetings, seminars, business launches, and corporate gaming functions.",
        "There is high demand for Audi Q7 SUV limo hire for tours to the Blue Mountain and Hunter Valley, providing a scenic, smooth drive for interstate and overseas tourists.",
        "Our experienced chauffeurs ensure a stress-free travel experience to the Blue Mountains and Hunter Valley, offering comfortable, air-conditioned rides in the clean and luxurious Audi 4WD limo.",
      ],
      overview: [
        "The Audi Q7 exudes style and sophistication with its redesigned and reimagined luxury SUV design.",
        "Powered by a 3.60-liter supercharged TFSI engine offering 252 and 333 HP, the Audi Q7 is linked to an eight-speed Tiptronic transmission, providing a dynamic and powerful driving experience.",
        "The dynamic body lines of the Audi Q7 create a wide, sporty appearance that is both rugged and refined, perfect for those who value both performance and luxury.",
        "Intelligent design and luxury features provide an exceptional level of comfort and assurance, delivering a superior driving experience.",
        "A sophisticated array of technology in the Audi Q7 ensures a safer drive, with assistance systems for every aspect of your journey.",
        "The ultra-lightweight construction of the Q7, including aluminium components, improves fuel efficiency, agility, and responsiveness, enhancing both performance and comfort.",
        "The bold exterior of the Audi Q7 exudes a confident presence, with clearly defined surfaces and taut lines giving the body an athletic and timeless appearance.",
        "The Audi Q7 3.0 TDI 200kW comes standard with the Audi virtual cockpit, a 12.3-inch digital instrument cluster that replaces traditional dials, offering a modern driving experience.",
        "The spaciousness and sophistication of the Q7 are unmatched, comfortably accommodating up to 6 passengers, and with the touch of a button, the third-row seats can be individually folded down to create an even more generous luggage compartment.",
      ],
      amenities: [
        "20” 10-spoke-star design grey/polished-finish wheels with run-flat tyres.",
        "Full LED headlights & Top view camera system for enhanced visibility and safety.",
        "BOSE 3D Sound System with 19 speakers, providing a premium audio experience with the BOSE® Advanced Sound System.",
        "Automatic Start-Stop function, which stops the engine when the car is at a standstill in heavy traffic for improved fuel efficiency.",
        "iPhone, Bluetooth, and Sirius radio connectivity for seamless entertainment and device integration.",
        "Perimeter leather seating for up to 6 passengers, providing a comfortable travel experience.",
        "One of the smoothest and easiest SUVs to drive for its size.",
        "Middle row seats that comfortably accommodate 2 people.",
        "Perfect car for a family of 4, offering big space for luggage.",
        "Wood grain and aluminium highlights in the dash and door surrounds for an elegant interior design.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Audi Q7 SUV Limousine Hire",
        "Blue Mountain Tour in a SUV",
        "Hunter Valley Tour in a SUV",
        "Cruise Ship Transfers",
        "Luxury SUV Limo",
        "Door to Door Services",
      ],
    },

    {
      slug: "bmw-x7-(suv)",
      name: "BMW X7 (SUV)",
      price: "$133.2/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image: "https://sydneylimousineservice.com/img/fleets/bmw-x7/bmw-x7.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$133.2/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1065.6/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/left.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/interior.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/front.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/bmw-x7/back.png",
      ],
    },

    {
      slug: "mercedes-benz-gle",
      name: "Mercedes-Benz GLE",
      price: "$133.2/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/mercedes-benz-gle.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$133.2/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1065.6/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/left.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/interior.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/front.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-gle/back.png",
      ],
      whyChoose: [
        "The European Luxury SUV Mercedes GLE is a popular spacious car for a family of four, offering room for four large pieces of luggage, making it ideal for airport transfers, cruise ship transfers, or point-to-point services.",
        "The Mercedes GLE offers longer leg space, a powerful drive, and a remarkably elegant interior with sophisticated leather seats, ensuring a stylish and comfortable travel experience.",
        "The Mercedes GLE comfortably accommodates up to 6 passengers, and for four people with large luggage, the third-row seats can be folded down individually to create a generous luggage compartment.",
        "The Mercedes GLE can be hired for wedding car services, allowing you to feel like royalty on your special day and make your wedding memorable with this luxury SUV.",
        "Our elegant Mercedes GLE is a perfect choice for special day hires, ensuring that you arrive at your venue in comfort and style.",
        "We offer Mercedes GLE luxury SUV limo hire at competitive prices, making it an excellent option for corporate travelers in the corporate community.",
        "The Mercedes GLE is suitable for transportation to corporate events, including business meetings, seminars, business launches, and corporate gaming functions.",
        "There is high demand for Mercedes GLE SUV limo hire for tours to the Blue Mountain and Hunter Valley, providing a scenic, smooth drive for interstate and overseas tourists.",
        "Our experienced chauffeurs offer stress-free travel experiences to the Blue Mountains and Hunter Valley, providing comfortable, air-conditioned rides in the clean and luxurious Mercedes 4WD limo.",
      ],
      overview: [
        "Mercedes-Benz GLE is a large crossover wagon that during its run offer a wide choice of engines ranging from a diesel V6 to a powerhouse AMG V8. Most GLE are with all-wheel drive and rear-drive model. The most recent version of this model came in a choice of V6. This car is a seven-speed automatic transmission. A 2+2+2 seating arrangement for a total capacity of six people excluding the driver is standard, with a 2+3+2 configuration optional. ",
      ],
      amenities: [
        "Perimeter leather seating for up to 6 passengers, providing a comfortable travel experience.",
        "Premium Stereo System with iPod interface and 4 USB plug-ins for enhanced entertainment.",
        "Rear Luggage Compartment capable of carrying a substantial amount of luggage.",
        "Offers open space that is flexible and can be configured for passengers or luggage.",
        "Optional front and rear parking sensors with a camera for added convenience and safety.",
        "One of the smoothest and easiest SUVs to drive for its size.",
        "Middle row seats that comfortably accommodate 2 people.",
        "Perfect car for a family of 4, offering plenty of space for luggage.",
        "iPod, Bluetooth, and Sirius radio connectivity for seamless entertainment.",
        "Raw wood grain and aluminium highlights in the dash and door surrounds for a refined interior.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Mercedes Class SUV Limousine Hire",
        "Blue Mountain Tour in a SUV",
        "Hunter Valley Tour in a SUV",
        "Cruise Ship Transfers",
        "Luxury SUV Limo",
        "Door to Door Services",
      ],
    },

    {
      slug: "lexus-rx-400hl",
      name: "Lexus RX 400hl",
      price: "$133.2/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/lexus-rx-400hl.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$133.2/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1065.6/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/left.png",
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/interior.png",
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/front.png",
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/lexus-rx-400hl/back.png",
      ],
      whyChoose: [
        "The top-of-the-line luxury Lexus 400hL is a spacious car for four people, providing a comfortable travel experience for airport transfers, corporate transportation, or point-to-point services.",
        "The Lexus 400hL offers a luxurious atmosphere with ample space, enhancing rear seat comfort and providing a spacious trunk for large luggage, ensuring a comfortable journey.",
        "With its high performance and elegant design, the Lexus 400hL ensures a luxurious and enjoyable transportation experience, perfect for both personal and corporate occasions.",
        "Our Lexus 400hL for hire in Sydney is an excellent choice for special occasions such as dates, important corporate meetings, or weddings, offering sophistication and luxury.",
        "Whether you're a corporate executive traveling extensively or occasionally for work, the Lexus 400hL is a professional and stylish choice for regular transportation.",
        "Make your wedding day special by choosing the Lexus 400hL as your wedding car, adding elegance and class to your celebration for a memorable and stylish entrance.",
        "Our Lexus 400hL is suitable for other special occasions, providing elegance and comfort for your greatest expectations.",
        "We offer Lexus 400hL luxury sedan limo hire at competitive prices for corporate travelers, with top-notch limousine service for corporate events, business meetings, and seminars.",
        "Experience a scenic and stress-free drive to destinations like the Blue Mountains and Hunter Valley in the Lexus 400hL, enjoying a smooth ride in comfort and style.",
      ],
      overview: [
        "The Lexus 400hL cabin represents the epitome of top luxury, featuring exquisite materials and finishes throughout for a premium feel.",
        "Exceptional comfort is ensured, with options such as reclining rear seats for the ultimate limousine ride, enhancing passenger experience.",
        "The Lexus 400hL boasts an elegant and dynamic design, with distinctive features like the iconic Lexus emblem, embodying sophistication and style.",
        "A preferred choice in the limousine industry, the Lexus 400hL is known for its hi-tech developments, with the latest model pushing technology and efficiency to new heights.",
        "The newest Lexus 400hL features a streamlined appearance, with a large front grille inspired by cutting-edge design concepts for a modern look.",
        "LED lights are used exclusively both inside and out, setting a new standard in the automotive industry and enhancing the car's visual appeal.",
        "Sculpted character lines and integrated exhaust tips emphasize the sporty and refined exterior of the Lexus 400hL, while the spacious interior ensures maximum comfort.",
        "The Lexus 400hL is equipped with advanced technology, making it both luxurious and efficient, perfect for those who demand the best in automotive design.",
      ],
      amenities: [
        "Perceived as a style icon in the luxury car segment.",
        "Intelligent electronic system for enhanced vehicle control and safety.",
        "Advanced sensor systems that maintain a safe distance from the vehicle in front.",
        "Night view assist system providing clear vision in challenging conditions like fog or darkness.",
        "Airbags for both the driver and passengers, ensuring a high level of safety.",
        "4-Wheel ABS (Anti-Lock Braking System) to prevent sudden skidding and improve vehicle control.",
        "Integration with a 7 surround music system for an immersive audio experience.",
        "Wood grain and aluminum highlights in the dash and door surrounds for a luxurious interior design.",
        "Split-view facility, an innovative technology that displays different images on a single screen.",
      ],
      servicesOffered: [
        "Corporate Transportation",
        "Chauffeur Service",
        "City Tours",
        "Weddings Car Services",
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Lexus 400hL Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door-to-Door Services",
        "Lexus 400hL Limo",
      ],
    },

    {
      slug: "mercedes-benz-v-class",
      name: "Mercedes-Benz V Class",
      price: "$155.4/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/mercedes-benz-v-class.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$155.4/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1243.2/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/interior.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/front.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/front-right%20(2).png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/mercedes-benz-v-class/back.png",
      ],
      whyChoose: [
        "The European luxury Mercedes Van is a popular people mover for a family of 7, with space for 5 to 6 large pieces of luggage, ideal for airport transfers, cruise ship transfers, weddings, school formals, or point-to-point services.",
        "The Mercedes Viano or V Class 7 Passengers van features an impressive interior standing height, providing ample room to move and ensuring comfort for all passengers.",
        "The van offers a spacious rear storage area and ergonomic, durable rear passenger seating with individual headrests in each position, enhancing comfort and safety.",
        "With great accessibility, spacious storage, and an impressive interior height, passengers can move in and out comfortably.",
        "The Mercedes Van has a low step-in height, with seating for 1 next to the driver, 3 in the middle row, and 3 in the back row, making it ideal for group travel.",
        "Optional rear air conditioning ensures a comfortable ride without perspiration, perfect for longer journeys or warmer climates.",
        "Mercedes luxury vans can be hired for wedding car services, adding elegance and comfort to your special day.",
        "Our Mercedes Viano or V Class is a perfect choice for special day hires, ensuring you arrive at your venue in comfort and style.",
        "We offer Mercedes van limo hire at competitive prices for corporate travelers, providing top-notch limousine services for corporate events, business meetings, and seminars.",
        "There is high demand for Mercedes van limo hire for tours to the Blue Mountain and Hunter Valley, providing a smooth and scenic drive for interstate and overseas tourists.",
        "Our experienced chauffeurs ensure stress-free travel to the Blue Mountains and Hunter Valley, providing clean, comfortable, and air-conditioned rides in the Mercedes van limo.",
      ],
      overview: [
        "The Mercedes-Benz V-Class is an exceptionally practical and versatile luxury van, setting new standards in key areas while maintaining Mercedes-Benz's renowned safety, quality, and reliability.",
        "As the first choice for luxury van transportation, the Mercedes V Class or Viano offers maximum capacity for 7 passengers, combining style, safety, and innovation.",
        "The Mercedes Viano or V Class is powered by a turbo-diesel engine, delivering class-leading power, economy, and refinement for an effortless driving experience.",
        "With a powerful exterior and ergonomic, variable interior design, the V-Class offers intelligent assistance and safety systems, as well as the MBUX multimedia system to meet the highest standards.",
        "The efficient, powerful engines and automatic transmission of the V-Class turn every journey into a pleasurable experience.",
        "The turbo-diesel engine provides impressive performance, with 165 kW of power and 440 Nm of torque between 1600 and 2400 rpm, ensuring the van can handle heavy loads effortlessly.",
        "The V-Class exterior is refined with 17-inch or 18-inch light-alloy wheels, high-quality LED headlamps, and bi-color tail lamps, enhancing both aesthetics and functionality.",
        "The left-hand sliding door adds flexibility for easier entry and exit, while the separately opening rear window makes loading the vehicle more convenient.",
        "The interior of the V-Class features comfort seats in Lugano leather and trim elements in a twin stripe design, offering seating for six or more passengers with a choice of bucket or bench seating.",
        "The V-Class offers customizable seating options, with the ability to install one, two, or three seats in both rear rows. Standard seating includes two individual seats and a 3-passenger bench seat in the rear.",
        "For larger groups, the spacious body length of the V-Class can accommodate two rear 3-passenger bench seats, turning it into an eight-seater vehicle, providing maximum flexibility and comfort.",
      ],
      amenities: [
        "Perimeter leather seating for 7 passengers, providing a comfortable travel experience.",
        "Premium Stereo System with iPod interface and 4 USB plug-ins for enhanced entertainment.",
        "Rear Luggage Compartment capable of carrying a substantial amount of luggage.",
        "Open space that is flexible and can be configured for people, cargo, or both.",
        "Optional front and rear parking sensors and a six-disc CD changer for added convenience and entertainment.",
        "One of the smoothest and easiest vans to drive for its size, ensuring a comfortable journey.",
        "Six rear seats that allow passengers to sit comfortably face to face.",
        "Perfect vehicle for small groups of travelers, offering ample space for luggage.",
        "Intelligent storage facility with spacious and versatile interiors.",
      ],
      servicesOffered: [
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Mercedes Van Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "Mercedes Van Limo",
        "Group Tour Services",
        "Corporate Car Hire",
        "Chauffeured Driven Services",
      ],
    },

    {
      slug: "mercedes-sprinter",
      name: "Mercedes Sprinter",
      price: "$177.6/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/sprinter/sprinter.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$$177.6/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$1420.8/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/sprinter/left.png",
        "https://sydneylimousineservice.com/img/fleets/sprinter/interior.png",
        "https://sydneylimousineservice.com/img/fleets/sprinter/front.png",
        "https://sydneylimousineservice.com/img/fleets/sprinter/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/sprinter/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/sprinter/back.png",
      ],
      whyChoose: [
        "The luxury Mercedes Sprinter people mover can accommodate 11 passengers with ample luggage space, making it perfect for airport transfers for groups, corporate events, or personal celebrations.",
        "The Mercedes Sprinter van is ideal for airport transportation or shuttling passengers between locations, such as large group transfers, wedding transfer services, school formals, or corporate functions.",
        "This van seats 11 adults with luggage, offering front and rear air conditioning and tinted windows for added comfort and security, making it one of the most elegant and modern options for group transportation.",
        "For business or pleasure, the Mercedes-Benz Sprinter, along with our professional staff, provides a luxurious experience for all passengers.",
        "The Mercedes Sprinter can be hired for wedding functions, transferring groups from the church to the venue, adding elegance and comfort to your special day.",
        "We offer Mercedes Sprinter limo hire at competitive prices, ideal for corporate travelers looking for top-tier transportation for corporate events, meetings, seminars, business launches, or gaming functions.",
        "The Mercedes Sprinter is very popular for group tour hires, especially for tours to the Blue Mountains and Hunter Valley, offering a scenic and smooth ride.",
        "Our experienced chauffeurs ensure a stress-free travel experience with comfortable, air-conditioned Mercedes Sprinter vans, perfect for sightseeing tours to the Blue Mountains and Hunter Valley.",
      ],
      overview: [
        "The Mercedes Sprinter offers all the amenities of a luxury vehicle and much more, providing the feel of a stretch limousine.",
        "A large sliding door provides easy access, and its height allows passengers to stand and walk to their seat, offering more comfort than traditional limousines.",
        "The Sprinter comes with high-quality features, innovations, and connectivity that you expect from Mercedes-Benz, setting the benchmark in its class.",
        "With a reshaped grille, fenders, lights, and rear window, the Sprinter is designed for evolution, combining a modern look with functionality.",
        "The cabin area redefines comfort with ergonomic seats and a redesigned instrument cluster for an improved driving and passenger experience.",
        "Performance is top-tier, featuring turbocharged engines with options for 4-cylinder gasoline, 4-cylinder diesel, and 6-cylinder diesel engines, paired with a 7G-TRONIC 7-speed transmission.",
        "Safety features include Active Brake Assist, a rearview camera display, and multimedia touch-screen control, providing convenience and peace of mind.",
        "The Mercedes-Benz Sprinter is available in various body styles and seating arrangements, including Panel Van, Transfer Minibus, and Cab Chassis, offering versatility for different needs.",
      ],
      amenities: [
        "Perimeter leather seating for 11 passengers, providing a comfortable travel experience.",
        "Premium Stereo System with iPod interface and 4 USB plug-ins for enhanced entertainment.",
        "Rear Luggage Compartment, capable of carrying a substantial amount of luggage.",
        "Open space that is flexible and can be configured for people, cargo, or both.",
        "High roofing interior height of 6’6”, allowing most people to stand upright inside.",
        "Optional heated front seats, front and rear parking sensors, and a six-disc CD changer for added comfort and convenience.",
        "One of the smoothest and easiest vans to drive for its size, ensuring a comfortable journey.",
      ],
      servicesOffered: [
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Mercedes Van Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Sedan Limo",
        "Door to Door Services",
        "Mercedes Sprinter Van Limo",
        "Group Tour Services",
        "Mercedes Sprinter Transfers",
        "Corporate Car Hire",
        "Chauffeured Driven Services",
      ],
    },

    {
      slug: "stretch-chrysler-300C",
      name: "Stretch Chrysler 300C",
      price: "$600.0/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image:
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/chrysler-stretch.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$600.0/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$4800.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/left.jpg",
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/interior.jpg",
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/front.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/chrysler-stretch/back.jpg",
      ],
      whyChoose: [
        "The Chrysler 300C Stretch Limousine accommodates up to 11 passengers and comes in black or white, making it an elegant choice for any event with complimentary champagne.",
        "Perfect for special events, proms, weddings, or nights out, this traditional stretch limousine is equipped to meet your needs with comfort and style.",
        "Our Chrysler Stretch Limo service provides a luxurious experience for all ages, whether it's for a business meeting, prom, or any fashionable event.",
        "The Chrysler Stretch Limousine is especially popular for weddings, ensuring a memorable and elegant transportation experience for your special day.",
        "This limousine is also perfect for airport transportation or group transfers, wedding services, school formals, and corporate functions, offering comfort for up to 12 adults with air conditioning and tinted windows.",
        "The Chrysler 300C Stretch Limousine is one of the most elegant and modern transfer options for groups, providing a luxurious experience for both business and pleasure.",
        "We offer Chrysler 300C Stretch Limousine hire at competitive prices, catering to corporate travelers and providing top-tier limousine services for events like business meetings, seminars, and corporate launches.",
        "This limousine can also be hired for tours to the Blue Mountains and Hunter Valley, where our experienced chauffeur provides a scenic and smooth ride, ensuring stress-free travel in comfort and style.",
        "Our chauffeurs are well-experienced in providing sightseeing tours to the Blue Mountains and Hunter Valley, offering clean, comfortable, and air-conditioned rides in the Chrysler 300C Stretch Limousine.",
      ],
      overview: [
        "The Chrysler 300C Super Stretch Limousine features amazing jet doors and a soft leather interior, accommodating up to 12 passengers in luxury.",
        "The Chrysler 300C has a limousine body type with a 4-cylinder 3.6 L aspirated engine, providing 210KW @3650rpm and rear-wheel drive.",
        "With its long hood, aggressive grille, and 5-speed automatic transmission, the 300C Stretch Limousine delivers power to the rear wheels for a dynamic driving experience.",
        "The interior is accented with various color combinations, hardwood floors, and wet bars lining each side, offering a luxurious ambiance.",
        "Top-tier audio and video functionality allows passengers to enjoy thousands of songs from their favorite playlists while riding under the fiber optic lighting.",
        "The Chrysler 300C Stretch Limousine exudes style and sophistication with a bold exterior and clearly defined surfaces that give it an athletic, timeless, and unique appearance.",
        "With its wide, sporty look, the Chrysler 300C Stretch Limousine combines ruggedness and refinement, creating a confident presence on the road.",
        "The intelligent design and luxury features provide an exceptional level of comfort, making the Chrysler 300C Stretch Limousine a standout in driving experience and passenger satisfaction.",
        "A sophisticated array of technology enhances safety, with assistance systems covering every aspect of your journey.",
        "The Chrysler 300C Stretch Limousine offers unsurpassed spaciousness and sophistication, comfortably accommodating up to 12 passengers for any occasion.",
      ],
      amenities: [
        "Full-length custom wave bar console with isolated ice and champagne storage for a luxurious experience.",
        "TV and Stereo System with Dolby DTS digital surround sound for top-quality entertainment.",
        "Fibre optic lighting throughout the vehicle, along with a CD/DVD player for enhanced ambiance.",
        "Ground effect strobe and lights with a privacy partition for added comfort and discretion.",
        "Overhead control for both front and rear, with wrap-around leather couch seating for a stylish and comfortable interior.",
        "Touch screen controls to make the limousine's features easy to manage.",
        "Starlight ceiling offering a glittering, elegant look.",
        "1000-watt sound system, allowing passengers to enjoy their favorite beats in superior audio quality.",
      ],
      servicesOffered: [
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Chrysler Stretch Limousine Service",
        "Wedding Limousine",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Limo Hire",
        "Door to Door Services",
        "Chrysler Stretch Limousine Hire",
        "Group Tour Services",
        "Corporate Car Hire",
      ],
    },

    {
      slug: "stretch-hummer-h2",
      name: "Stretch Hummer H2",
      price: "$700.0/hr",
      category: "Luxury SUV",
      luggage: "4 Pax 2 Lugg/3 Pax 3 Lugg",
      features: [
        "Light Refreshment",
        "Leather Interior",
        "Comfortable Leg Space",
        "Tinted Window",
      ],
      image: "https://sydneylimousineservice.com/img/fleets/hummer/hummer.png",
      actions: {
        viewDetails: "View Details",
        quoteBook: "Quote & Book Now",
      },
      rateInfo: [
        {
          label: "Per Hour Rate",
          price: "$700.0/HOUR",

          description:
            "*All inclusive of GST, Tolls & Service Fee - 2 hours minimum booking",
        },
        {
          label: "Per Day Rate",
          price: "$5600.0/DAY",
          unit: "/DAY",
          description:
            "*All inclusive of GST, Tolls & Service Fee - 8 hours of service",
        },
      ],
      viewImage: [
        "https://sydneylimousineservice.com/img/fleets/hummer/left.jpg",
        "https://sydneylimousineservice.com/img/fleets/hummer/interior.jpg",
        "https://sydneylimousineservice.com/img/fleets/hummer/front.png",
        "https://sydneylimousineservice.com/img/fleets/hummer/front-right.png",
        "https://sydneylimousineservice.com/img/fleets/hummer/front-left.png",
        "https://sydneylimousineservice.com/img/fleets/hummer/back.jpg",
      ],
      whyChoose: [
        "The Hummer H2 is a luxurious stretch limousine service, ideal for proms, sweet sixteen, birthdays, bachelor and bachelorette parties, weddings, airport transfers, sightseeing tours, and more.",
        "We offer reasonable rates and a fleet of H2 Hummer Limos that can accommodate 14 passengers, providing a stylish and safe ride for events like prom night in Sydney.",
        "Our wedding limousines, including the H2 Hummer Stretch Limousine, are a popular choice, having transported hundreds of brides and grooms throughout the Sydney Metro Area.",
        "The Hummer Stretch Limousine is available for up to 14 passengers and is an elegant choice for any event, offering complimentary champagne for a luxurious experience.",
        "Our Hummer Stretch Limo service is suitable for business meetings, corporate client transfers, seminars, business launches, corporate gaming functions, and special events, ensuring a fashionable and safe trip.",
        "The Hummer Stretch Limousine is very popular for weddings, adding elegance and comfort to your special day to make it memorable.",
        "This vehicle is perfect for airport transportation or group transfers, wedding services, school formals, and corporate functions, seating 14 adults with air conditioning and tinted windows for added comfort and security.",
        "The Hummer Stretch Limousine is one of the most elegant and modern transfer options for groups, providing a luxurious experience for both business and pleasure.",
        "We offer Hummer Stretch Limousine hire at competitive prices for corporate travelers, with our professional chauffeurs providing top-tier limousine service.",
        "You can hire this limousine for tours to the Blue Mountains and Hunter Valley, where our experienced chauffeur provides a scenic and smooth drive in comfort and style.",
        "Our chauffeurs are well-experienced in providing sightseeing tours in the Blue Mountains and Hunter Valley, ensuring a clean, comfortable, and stress-free travel experience.",
      ],
      overview: [
        "The H2 Hummers are unique in their own right, with interiors accented in various color combinations, hardwood floors, and wet bars lining each side of the vehicle.",
        "Top-rate audio and video functionality, with thousands of songs from favorite playlists, paired with fiber optic lights, creates an entertaining ride in this luxurious limousine.",
        "The Hummer H2 Limousine is built with style and sophistication, driven by a 5967 CC 6-liter V8 engine with a multipoint injection fuel system, providing power and performance.",
        "The bold exterior of the Hummer H2 exudes a confident presence, with clearly defined surfaces, taut lines, and a body that is athletic, timeless, and unique.",
        "The Hummer's external dimensions include an overall length of 193”, width of 81”, height of 79”, and ground clearance of 10”, making it both rugged and refined.",
        "Driver and passenger power heated partial-painted door mirrors with automatic operation and indicator lights enhance the vehicle's functionality and style.",
        "Special black front and rear bumpers add to the Hummer's spectacular appearance, providing both protection and aesthetic appeal.",
        "The wide, sporty dynamic body line of the Hummer combines ruggedness with refinement, making it a standout on the road.",
        "Intelligent design and luxury features provide exceptional comfort and assurance, delivering an unmatched driving experience.",
        "A sophisticated array of technology enhances safety, with assistance systems covering every aspect of your journey.",
        "The spaciousness and sophistication of the Hummer H2 are unsurpassed, comfortably accommodating up to 14 passengers for any occasion.",
      ],
      amenities: [
        "Full-length custom wave bar console with isolated ice and champagne storage.",
        "Comfortable seats in the Hummer for a total of 14 passengers.",
        "Luxury leather seats that provide a comfortable and stylish ride.",
        "Disco floor with changing lights to enhance the party atmosphere during the trip.",
        "Sparkling lighting with fiber optic and neon lights for a visually exciting experience.",
        "Quad lasers and strobe lights, along with a mirrored ceiling, for an astonishing visual effect.",
        "Fitted with a state-of-the-art entertainment system for ultimate enjoyment.",
        "TV and stereo system with Dolby DTS digital surround sound for high-quality entertainment.",
        "Fibre optic lighting throughout, with CD/DVD player, ground effect strobe lights, and a privacy partition.",
        "Overhead control for both front and rear, with wrap-around leather couch seating for maximum comfort.",
        "1000-watt sound system to let you enjoy your favorite music with superior audio quality.",
      ],
      servicesOffered: [
        "Airport Pick Up and Drop Off",
        "Sydney Airport Transfers",
        "Hummer Limousine Hire",
        "Blue Mountain Tour",
        "Hunter Valley Tour",
        "Cruise Ship Transfers",
        "Luxury Hummer Limo",
        "Door to Door Services",
        "Hummer Limousine Service",
        "Group Tour Services",
        "Hummer Limousine Transfers",
        "Corporate Car Hire",
        "Chauffeured Driven Services",
      ],
    },
  ];

  return NextResponse.json(fleetData);
}
